FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

ENV BACKEND_PORT=8000
EXPOSE ${BACKEND_PORT}

CMD uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}
